# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20160718_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='desc',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='desc',
            field=models.CharField(default='foo', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='desc',
            field=models.CharField(default='foo', max_length=1024),
            preserve_default=False,
        ),
    ]
