version: '2'
services:
  api:
    extends:
      file: docker-compose.common.yml
      service: api
    links:
      - redis
      - postgres

  nginx:
    extends:
      file: docker-compose.common.yml
      service: nginx
    links:
      - api

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

  backup:
    extends:
      file: docker-compose.common.yml
      service: postgres
    environment:
      REPLICATION_MODE: backup
      REPLICATION_HOST: master
    links:
      - postgres:master
    volumes:
      - ./BACKUPS/postgresql.$DATE:/var/lib/postgresql

volumes:
  dbdata:
  staticdata:
