version: '2'
services:
  api:
    restart: always
    build: api
    expose:
      - 80
    volumes:
      - staticdata:/static
      - ./api/src:/api/src:rw
    environment:
      DEBUG: $API_DEBUG
      SECRET_KEY: $API_SECRET_KEY
      ADMIN_USER: $API_ADMIN_USER
      ADMIN_PASS: $API_ADMIN_PASS
      ADMIN_EMAIL: $API_ADMIN_EMAIL
      USE_WEBPACK_DEV_SERVER: $USE_WEBPACK_DEV_SERVER
      DB_NAME: $POSTGRES_NAME
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASS
      SERVER_NAME: $NGINX_SERVER_NAME
      QUIET_LOGS: $API_QUIET_LOGS

  frontend:
    restart: on-failure:3
    build: frontend
    environment:
      USE_WEBPACK_DEV_SERVER: $USE_WEBPACK_DEV_SERVER
    expose:
      - 80
    volumes:
      - staticdata:/static
      - ./frontend/src:/app/src:ro
      - ./frontend/bin:/usr/local/bin:ro

  nginx:
    restart: on-failure:3
    build: nginx
    environment:
      PORT: $NGINX_PORT
      SERVER_NAME: $NGINX_SERVER_NAME
      USE_WEBPACK_DEV_SERVER: $USE_WEBPACK_DEV_SERVER
      VERBOSE: $NGINX_VERBOSE
    ports:
      - $NGINX_PORT:$NGINX_PORT
    volumes:
      - staticdata:/static

  redis:
    restart: on-failure:3
    build: redis
    volumes:
      - ./redis/root/usr/local/bin/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./redis/root/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/root/usr/local/bin/entr.sh:/usr/local/bin/entr.sh:ro
    expose:
      - 6379

  postgres:
    restart: on-failure:3
    build: postgres
    environment:
      REPLICATION_MODE: master
      DEBUG: $POSTGRES_DEBUG
      REPLICATION_USER: $POSTGRES_REPL_USER
      REPLICATION_PASS: $POSTGRES_REPL_PASS
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASS
      DB_NAME: $POSTGRES_NAME
    expose:
      - 5432
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata:
  staticdata:
