version: '2'
services:
  app:
    restart: always
    build: app
    expose:
      - 80
      - 3000
    volumes:
      - staticdata:/static
      - ./app/sns_dashboard:/app
      - ./app/src:/src:ro
    environment:
      DEBUG: $APP_DEBUG
      SECRET_KEY: $APP_SECRET_KEY
      ADMIN_USER: $APP_ADMIN_USER
      ADMIN_PASS: $APP_ADMIN_PASS
      ADMIN_EMAIL: $APP_ADMIN_EMAIL
      USE_WEBPACK_DEV_SERVER: $APP_USE_WEBPACK_DEV_SERVER
      DB_NAME: $POSTGRES_NAME
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASS
      SERVER_NAME: $NGINX_SERVER_NAME

  nginx:
    restart: on-failure:3
    build: nginx
    environment:
      PORT: $NGINX_PORT
      SERVER_NAME: $NGINX_SERVER_NAME
      USE_WEBPACK_DEV_SERVER: $APP_USE_WEBPACK_DEV_SERVER
    ports:
      - $NGINX_PORT:$NGINX_PORT
    volumes:
      - staticdata:/static

  redis:
    restart: on-failure:3
    build: redis
    volumes:
      - ./redis/root/usr/local/bin/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./redis/root/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/root/usr/local/bin/entr.sh:/usr/local/bin/entr.sh:ro
    expose:
      - 6379

  postgres:
    restart: on-failure:3
    build: postgres
    environment:
      REPLICATION_MODE: master
      DEBUG: $POSTGRES_DEBUG
      REPLICATION_USER: $POSTGRES_REPL_USER
      REPLICATION_PASS: $POSTGRES_REPL_PASS
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASS
      DB_NAME: $POSTGRES_NAME
    expose:
      - 5432
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata:
  staticdata:
