app:
  restart: always
  build: app
  expose:
    - 80
    - 3000
  volumes:
    - staticdata:/static
    - ./app/sns_dashboard:/app
    - ./app/src:/src:ro
  env_file: config/env/local.env
  environment:
    - DEBUG=$APP_DEBUG
  links:
    - redis
    - postgres

nginx:
  restart: always
  build: nginx
  ports:
    - 80:80
  env_file: config/env/local.env
  volumes:
    - staticdata:/static
  links:
    - app

redis:
  restart: always
  build: redis
  expose:
    - 6379

postgres:
  restart: always
  image: sameersbn/postgresql:9.4-23
  env_file: config/env/local.env
  environment:
    - DEBUG=$DB_DEBUG
  expose:
    - 5432
  volumes:
    - dbdata:/var/lib/postgresql
