version: '2'
services:
  api:
    extends:
      file: docker-compose.common.yml
      service: api
    links:
      - redis
      - postgres

  frontend:
    extends:
      file: docker-compose.common.yml
      service: frontend

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

  nginx:
    extends:
      file: docker-compose.common.yml
      service: nginx
    links:
      - api
      - frontend

volumes:
  dbdata:
  staticdata:
