# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import src.reduction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text=b'The parameters that every configuration for this instrumentwill start with', verbose_name=b'base configuration parameters')),
            ],
            bases=(src.reduction.models.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text=b'The description/title of the configuration', max_length=1024, verbose_name=b'configuration description/title')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text=b'The date this configuration was created', verbose_name=b'configuration creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text=b'The date this configuration was last modified', verbose_name=b'configuration modification date')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text=b'The parameters for the configuration', verbose_name=b'configuration parameters')),
                ('instrument', models.ForeignKey(help_text=b'The instrument this configuration is for', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='catalog.Instrument', verbose_name=b"configuration's instrument")),
            ],
            bases=(src.reduction.models.AutoRepr, models.Model),
        ),
    ]
