# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.reduction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('reduction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(help_text=b'The user who created this configuration', on_delete=models.SET(src.reduction.models.get_sentinel_user), related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name=b"configuration's creator"),
        ),
        migrations.AddField(
            model_name='baseconfiguration',
            name='instrument',
            field=models.OneToOneField(help_text=b'The instrument this configuration is for', on_delete=django.db.models.deletion.CASCADE, to='catalog.Instrument', verbose_name=b'base configuration for instrument'),
        ),
    ]
