#!/usr/bin/with-contenv sh
set -euo pipefail

tee /etc/nginx/conf.d/default.conf <<EOF
log_format upstreamlog '[\$time_local] \$remote_addr - \$remote_user - \$server_name to: \$upstream_addr: \$request upstream_response_time \$upstream_response_time msec \$msec request_time \$request_time';

server {
    listen $PORT;
    server_name $SERVER_NAME;
    charset utf-8;

    error_log /dev/stdout;
    rewrite_log on;

    location /static {
        alias /static;
    }

$(if [ "$USE_WEBPACK_DEV_SERVER" = true ]; then cat <<EOF_WEBPACK; fi
    location /webpack/ {
        proxy_set_header Host \$host$([ ! "$PORT" = 80 ] && echo ":$PORT");
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host \$server_name;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_pass http://webpack/;
        access_log /dev/stdout upstreamlog;
    }
EOF_WEBPACK
)
    location / {
        proxy_pass http://app;
        proxy_set_header Host \$host$([ ! "$PORT" = 80 ] && echo ":$PORT");
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host \$server_name;
    }
}

$(if [ "$USE_WEBPACK_DEV_SERVER" = true ]; then cat <<EOF_WEBPACK; fi
upstream webpack {
    server app:3000;
}
EOF_WEBPACK
)

EOF

nginx
