# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether the facility is active and working in the dashboard', verbose_name='facility is active'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether the instrument is active and working in the dashboard', verbose_name='instrument is active'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='facility',
            field=models.ForeignKey(help_text='The facility the instrument is at (e.g. "SNS")', on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='catalog.Facility', verbose_name="instrument's facility"),
        ),
    ]
