# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:51
from __future__ import unicode_literals

import api.reduction.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='The description/title of the configuration', max_length=1024, verbose_name='configuration description/title')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this configuration was created', verbose_name='configuration creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date this configuration was last modified', verbose_name='configuration modification date')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The parameters for the configuration', verbose_name='configuration parameters')),
                ('instrument', models.ForeignKey(help_text='The instrument this configuration is for', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='catalog.Instrument', verbose_name="configuration's instrument")),
                ('user', models.ForeignKey(help_text='The user who created this configuration', on_delete=models.SET(api.reduction.models.get_sentinel_user), related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name="configuration's creator")),
            ],
        ),
    ]
