# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('name', models.CharField(help_text=b'Facility name (e.g. "SNS" or "HFIR")', max_length=32, primary_key=True, serialize=False, verbose_name=b'facility name')),
                ('description', models.CharField(help_text=b'Facility description (e.g. "Spallation Neutron Source")', max_length=1024, verbose_name=b'facility description')),
                ('active', models.BooleanField(default=False, help_text=b'Whether the facility is active and working in the dashboard', verbose_name=b'facility is active')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Facilities',
            },
            bases=(src.catalog.models.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text=b'Instrument name (e.g. "EQSANS" or "BioSANS")', max_length=32, primary_key=True, serialize=False, verbose_name=b'instrument name')),
                ('description', models.CharField(help_text=b'Instrument description (e.g. "Backscattering Spectrometer")', max_length=1024, verbose_name=b'instrument description')),
                ('beamline', models.CharField(help_text=b'Beamline that goes into instrument (e.g. "BL-2")', max_length=32, verbose_name=b'instrument beamline')),
                ('type', models.CharField(help_text=b'Instrument type (e.g. "SANS")', max_length=32, verbose_name=b'instrument type')),
                ('icat_name', models.CharField(help_text=b'Name used for querying ICAT server (e.g. "EQSANS")', max_length=32, verbose_name=b'instrument icat name')),
                ('ldap_name', models.CharField(help_text=b'Name used for querying LDAP server', max_length=32, verbose_name=b'instrument ldap name')),
                ('drive_name', models.CharField(help_text=b'Name used for loading files from shared filesystem', max_length=32, verbose_name=b'instrument drive name')),
                ('reduction_available', models.BooleanField(default=False, help_text=b'Whether the instrument can do reductions', verbose_name=b'instrument can do reductions')),
                ('active', models.BooleanField(default=False, help_text=b'Whether the instrument is active and working in the dashboard', verbose_name=b'instrument is active')),
                ('facility', models.ForeignKey(help_text=b'The facility the instrument is at (e.g. "SNS")', on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='catalog.Facility', verbose_name=b"instrument's facility")),
            ],
            options={
                'ordering': ('beamline',),
            },
            bases=(src.catalog.models.AutoRepr, models.Model),
        ),
    ]
